// lessonsData.js

const lessonsData = {
    "Информатика": {
        "5 Класс": [
            { id: 1, title: "Урок 1. НЕТ ЗАДАНИЯ", url: "https://example.com/info5-1" },
            { id: 2, title: "Урок 2. НЕТ ЗАДАНИЯ", url: "https://example.com/info5-2" },
            { id: 3, title: "Урок 3. НЕТ ЗАДАНИЯ", url: "https://example.com/info5-3" },
            { id: 4, title: "Урок 4. История ЭВМ", url: "https://docs.google.com/forms/d/e/1FAIpQLSc6YnycVdmb9iZR7ehGa45nPQEW_14t2Fdwx0fSPTqbIV49MQ/viewform?usp=header" },
            { id: 5, title: "Урок 5. ПО и ИИ", url: "https://docs.google.com/forms/d/e/1FAIpQLScjLiQP1K8iTg_bTrFqkeLSBzBlRCL-tw5qwG9dDIvfukGIAg/viewform?usp=header" },
            { id: 6, title: "Урок 6. Шифрование информации", url: "https://forms.gle/aLWLp2MRBdeqRp34A" },
            { id: 7, title: "Урок 7. НЕТ ЗАДАНИЯ", url: "https://example.com/info5-3" },
            { id: 8, title: "Урок 8. НЕТ ЗАДАНИЯ", url: "https://example.com/info5-3" },
            { id: 9, title: "Урок 9. НЕТ ЗАДАНИЯ", url: "https://example.com/robot8-1" },
            { id: 10, title: "Урок 10. НЕТ ЗАДАНИЯ", url: "https://example.com/robot8-1" },
            { id: 11, title: "Урок 11. НЕТ ЗАДАНИЯ", url: "https://example.com/robot8-1" },
            { id: 12, title: "Урок 12. НЕТ ЗАДАНИЯ", url: "https://example.com/robot8-1" },
            { id: 13, title: "Урок 13. НЕТ ЗАДАНИЯ", url: "https://example.com/robot8-1" },
            { id: 14, title: "Урок 14. НЕТ ЗАДАНИЯ", url: "https://example.com/robot8-1" },
            { id: 15, title: "Урок 15. НЕТ ЗАДАНИЯ", url: "https://example.com/robot8-1" },
            { id: 16, title: "Урок 16. НЕТ ЗАДАНИЯ", url: "https://example.com/robot8-1" },
            { id: 17, title: "Урок 17. НЕТ ЗАДАНИЯ", url: "https://example.com/robot8-1" },
            { id: 18, title: "Урок 18. НЕТ ЗАДАНИЯ", url: "https://example.com/robot8-1" },
            { id: 19, title: "Урок 19. НЕТ ЗАДАНИЯ", url: "https://example.com/robot8-1" },
            { id: 20, title: "Урок 20. НЕТ ЗАДАНИЯ", url: "https://example.com/robot8-1" },
            { id: 21, title: "Урок 21. НЕТ ЗАДАНИЯ", url: "https://example.com/robot8-1" },
            { id: 22, title: "Урок 22. НЕТ ЗАДАНИЯ", url: "https://example.com/robot8-1" },
            { id: 23, title: "Урок 23. НЕТ ЗАДАНИЯ", url: "https://example.com/robot8-1" },
            { id: 24, title: "Урок 24. НЕТ ЗАДАНИЯ", url: "https://example.com/robot8-1" },
            { id: 25, title: "Урок 25. НЕТ ЗАДАНИЯ", url: "https://example.com/robot8-1" },
            { id: 26, title: "Урок 26. НЕТ ЗАДАНИЯ", url: "https://example.com/robot8-1" },
            { id: 27, title: "Урок 27. НЕТ ЗАДАНИЯ", url: "https://example.com/robot8-1" },
            { id: 28, title: "Урок 28. НЕТ ЗАДАНИЯ", url: "https://example.com/robot8-1" },
            { id: 29, title: "Урок 29. НЕТ ЗАДАНИЯ", url: "https://example.com/robot8-1" },
            { id: 30, title: "Урок 30. НЕТ ЗАДАНИЯ", url: "https://example.com/robot8-1" },
            { id: 31, title: "Урок 31. НЕТ ЗАДАНИЯ", url: "https://example.com/robot8-1" },
            { id: 32, title: "Урок 32. НЕТ ЗАДАНИЯ", url: "https://example.com/robot8-1" },
            { id: 33, title: "Урок 33. НЕТ ЗАДАНИЯ", url: "https://example.com/robot8-1" },
            { id: 34, title: "Урок 34. НЕТ ЗАДАНИЯ", url: "https://example.com/robot8-1" },
            // Добавьте остальные уроки до 34...
        ],
        "6 Класс": [
            { id: 1, title: "Урок 1. НЕТ ЗАДАНИЯ", url: "https://example.com/info6-1" },
            { id: 2, title: "Урок 2. НЕТ ЗАДАНИЯ", url: "https://example.com/info6-2" },
            { id: 3, title: "Урок 3. Системный блок и память", url: "https://forms.gle/b1Gy2G312awj6GC36" },
            { id: 4, title: "Урок 4. Системный блок и память. Практикум", url: "https://docs.google.com/forms/d/e/1FAIpQLSdFIdtHqAPwHSKTTprdYLlf64WvBeBclLcUcagEH1yCqLjVyA/viewform?usp=header" },
            { id: 5, title: "Урок 5. Файловая система", url: "https://docs.google.com/forms/d/e/1FAIpQLSc4erjFynGwAdUHLnWFAeETYb6lz_Lx2VPaf148RS4KkcGM5A/viewform?usp=header" },
            { id: 6, title: "Урок 6. НЕТ ЗАДАНИЯ", url: "https://example.com/robot8-1" },
            { id: 7, title: "Урок 7. НЕТ ЗАДАНИЯ", url: "https://example.com/robot8-1" },
            { id: 8, title: "Урок 8. НЕТ ЗАДАНИЯ", url: "https://example.com/robot8-1" },
            { id: 9, title: "Урок 9. НЕТ ЗАДАНИЯ", url: "https://example.com/robot8-1" },
            { id: 10, title: "Урок 10. НЕТ ЗАДАНИЯ", url: "https://example.com/robot8-1" },
            { id: 11, title: "Урок 11. НЕТ ЗАДАНИЯ", url: "https://example.com/robot8-1" },
            { id: 12, title: "Урок 12. НЕТ ЗАДАНИЯ", url: "https://example.com/robot8-1" },
            { id: 13, title: "Урок 13. НЕТ ЗАДАНИЯ", url: "https://example.com/robot8-1" },
            { id: 14, title: "Урок 14. НЕТ ЗАДАНИЯ", url: "https://example.com/robot8-1" },
            { id: 15, title: "Урок 15. НЕТ ЗАДАНИЯ", url: "https://example.com/robot8-1" },
            { id: 16, title: "Урок 16. НЕТ ЗАДАНИЯ", url: "https://example.com/robot8-1" },
            { id: 17, title: "Урок 17. НЕТ ЗАДАНИЯ", url: "https://example.com/robot8-1" },
            { id: 18, title: "Урок 18. НЕТ ЗАДАНИЯ", url: "https://example.com/robot8-1" },
            { id: 19, title: "Урок 19. НЕТ ЗАДАНИЯ", url: "https://example.com/robot8-1" },
            { id: 20, title: "Урок 20. НЕТ ЗАДАНИЯ", url: "https://example.com/robot8-1" },
            { id: 21, title: "Урок 21. НЕТ ЗАДАНИЯ", url: "https://example.com/robot8-1" },
            { id: 22, title: "Урок 22. НЕТ ЗАДАНИЯ", url: "https://example.com/robot8-1" },
            { id: 23, title: "Урок 23. НЕТ ЗАДАНИЯ", url: "https://example.com/robot8-1" },
            { id: 24, title: "Урок 24. НЕТ ЗАДАНИЯ", url: "https://example.com/robot8-1" },
            { id: 25, title: "Урок 25. НЕТ ЗАДАНИЯ", url: "https://example.com/robot8-1" },
            { id: 26, title: "Урок 26. НЕТ ЗАДАНИЯ", url: "https://example.com/robot8-1" },
            { id: 27, title: "Урок 27. НЕТ ЗАДАНИЯ", url: "https://example.com/robot8-1" },
            { id: 28, title: "Урок 28. НЕТ ЗАДАНИЯ", url: "https://example.com/robot8-1" },
            { id: 29, title: "Урок 29. НЕТ ЗАДАНИЯ", url: "https://example.com/robot8-1" },
            { id: 30, title: "Урок 30. НЕТ ЗАДАНИЯ", url: "https://example.com/robot8-1" },
            { id: 31, title: "Урок 31. НЕТ ЗАДАНИЯ", url: "https://example.com/robot8-1" },
            { id: 32, title: "Урок 32. НЕТ ЗАДАНИЯ", url: "https://example.com/robot8-1" },
            { id: 33, title: "Урок 33. НЕТ ЗАДАНИЯ", url: "https://example.com/robot8-1" },
            { id: 34, title: "Урок 34. НЕТ ЗАДАНИЯ", url: "https://example.com/robot8-1" },
        ],
        "7 Класс": [
            { id: 1, title: "Урок 1. НЕТ ЗАДАНИЯ", url: "https://example.com/info7-1" },
            { id: 2, title: "Урок 2. НЕТ ЗАДАНИЯ", url: "https://example.com/robot8-1" },
            { id: 3, title: "Урок 3. НЕТ ЗАДАНИЯ", url: "https://example.com/robot8-1" },
            { id: 4, title: "Урок 4. НЕТ ЗАДАНИЯ", url: "https://example.com/robot8-1" },
            { id: 5, title: "Урок 5. НЕТ ЗАДАНИЯ", url: "https://example.com/robot8-1" },
            { id: 6, title: "Урок 6. НЕТ ЗАДАНИЯ", url: "https://example.com/robot8-1" },
            { id: 7, title: "Урок 7. НЕТ ЗАДАНИЯ", url: "https://example.com/robot8-1" },
            { id: 8, title: "Урок 8. НЕТ ЗАДАНИЯ", url: "https://example.com/robot8-1" },
            { id: 9, title: "Урок 9. НЕТ ЗАДАНИЯ", url: "https://example.com/robot8-1" },
            { id: 10, title: "Урок 10. НЕТ ЗАДАНИЯ", url: "https://example.com/robot8-1" },
            { id: 11, title: "Урок 11. НЕТ ЗАДАНИЯ", url: "https://example.com/robot8-1" },
            { id: 12, title: "Урок 12. НЕТ ЗАДАНИЯ", url: "https://example.com/robot8-1" },
            { id: 13, title: "Урок 13. НЕТ ЗАДАНИЯ", url: "https://example.com/robot8-1" },
            { id: 14, title: "Урок 14. НЕТ ЗАДАНИЯ", url: "https://example.com/robot8-1" },
            { id: 15, title: "Урок 15. НЕТ ЗАДАНИЯ", url: "https://example.com/robot8-1" },
            { id: 16, title: "Урок 16. НЕТ ЗАДАНИЯ", url: "https://example.com/robot8-1" },
            { id: 17, title: "Урок 17. НЕТ ЗАДАНИЯ", url: "https://example.com/robot8-1" },
            { id: 18, title: "Урок 18. НЕТ ЗАДАНИЯ", url: "https://example.com/robot8-1" },
            { id: 19, title: "Урок 19. НЕТ ЗАДАНИЯ", url: "https://example.com/robot8-1" },
            { id: 20, title: "Урок 20. НЕТ ЗАДАНИЯ", url: "https://example.com/robot8-1" },
            { id: 21, title: "Урок 21. НЕТ ЗАДАНИЯ", url: "https://example.com/robot8-1" },
            { id: 22, title: "Урок 22. НЕТ ЗАДАНИЯ", url: "https://example.com/robot8-1" },
            { id: 23, title: "Урок 23. НЕТ ЗАДАНИЯ", url: "https://example.com/robot8-1" },
            { id: 24, title: "Урок 24. НЕТ ЗАДАНИЯ", url: "https://example.com/robot8-1" },
            { id: 25, title: "Урок 25. НЕТ ЗАДАНИЯ", url: "https://example.com/robot8-1" },
            { id: 26, title: "Урок 26. НЕТ ЗАДАНИЯ", url: "https://example.com/robot8-1" },
            { id: 27, title: "Урок 27. НЕТ ЗАДАНИЯ", url: "https://example.com/robot8-1" },
            { id: 28, title: "Урок 28. НЕТ ЗАДАНИЯ", url: "https://example.com/robot8-1" },
            { id: 29, title: "Урок 29. НЕТ ЗАДАНИЯ", url: "https://example.com/robot8-1" },
            { id: 30, title: "Урок 30. НЕТ ЗАДАНИЯ", url: "https://example.com/robot8-1" },
            { id: 31, title: "Урок 31. НЕТ ЗАДАНИЯ", url: "https://example.com/robot8-1" },
            { id: 32, title: "Урок 32. НЕТ ЗАДАНИЯ", url: "https://example.com/robot8-1" },
            { id: 33, title: "Урок 33. НЕТ ЗАДАНИЯ", url: "https://example.com/robot8-1" },
            { id: 34, title: "Урок 34. НЕТ ЗАДАНИЯ", url: "https://example.com/robot8-1" },
        ],
        "8 Класс": [
            { id: 1, title: "Урок 1. НЕТ ЗАДАНИЯ", url: "https://example.com/robot8-1" },
            { id: 2, title: "Урок 2. НЕТ ЗАДАНИЯ", url: "https://example.com/robot8-1" },
            { id: 3, title: "Урок 3. НЕТ ЗАДАНИЯ", url: "https://example.com/robot8-1" },
            { id: 4, title: "Урок 4. НЕТ ЗАДАНИЯ", url: "https://example.com/robot8-1" },
            { id: 5, title: "Урок 5. НЕТ ЗАДАНИЯ", url: "https://example.com/robot8-1" },
            { id: 6, title: "Урок 6. НЕТ ЗАДАНИЯ", url: "https://example.com/robot8-1" },
            { id: 7, title: "Урок 7. НЕТ ЗАДАНИЯ", url: "https://example.com/robot8-1" },
            { id: 8, title: "Урок 8. НЕТ ЗАДАНИЯ", url: "https://example.com/robot8-1" },
            { id: 9, title: "Урок 9. НЕТ ЗАДАНИЯ", url: "https://example.com/robot8-1" },
            { id: 10, title: "Урок 10. НЕТ ЗАДАНИЯ", url: "https://example.com/robot8-1" },
            { id: 11, title: "Урок 11. НЕТ ЗАДАНИЯ", url: "https://example.com/robot8-1" },
            { id: 12, title: "Урок 12. НЕТ ЗАДАНИЯ", url: "https://example.com/robot8-1" },
            { id: 13, title: "Урок 13. НЕТ ЗАДАНИЯ", url: "https://example.com/robot8-1" },
            { id: 14, title: "Урок 14. НЕТ ЗАДАНИЯ", url: "https://example.com/robot8-1" },
            { id: 15, title: "Урок 15. НЕТ ЗАДАНИЯ", url: "https://example.com/robot8-1" },
            { id: 16, title: "Урок 16. НЕТ ЗАДАНИЯ", url: "https://example.com/robot8-1" },
            { id: 17, title: "Урок 17. НЕТ ЗАДАНИЯ", url: "https://example.com/robot8-1" },
            { id: 18, title: "Урок 18. НЕТ ЗАДАНИЯ", url: "https://example.com/robot8-1" },
            { id: 19, title: "Урок 19. НЕТ ЗАДАНИЯ", url: "https://example.com/robot8-1" },
            { id: 20, title: "Урок 20. НЕТ ЗАДАНИЯ", url: "https://example.com/robot8-1" },
            { id: 21, title: "Урок 21. НЕТ ЗАДАНИЯ", url: "https://example.com/robot8-1" },
            { id: 22, title: "Урок 22. НЕТ ЗАДАНИЯ", url: "https://example.com/robot8-1" },
            { id: 23, title: "Урок 23. НЕТ ЗАДАНИЯ", url: "https://example.com/robot8-1" },
            { id: 24, title: "Урок 24. НЕТ ЗАДАНИЯ", url: "https://example.com/robot8-1" },
            { id: 25, title: "Урок 25. НЕТ ЗАДАНИЯ", url: "https://example.com/robot8-1" },
            { id: 26, title: "Урок 26. НЕТ ЗАДАНИЯ", url: "https://example.com/robot8-1" },
            { id: 27, title: "Урок 27. НЕТ ЗАДАНИЯ", url: "https://example.com/robot8-1" },
            { id: 28, title: "Урок 28. НЕТ ЗАДАНИЯ", url: "https://example.com/robot8-1" },
            { id: 29, title: "Урок 29. НЕТ ЗАДАНИЯ", url: "https://example.com/robot8-1" },
            { id: 30, title: "Урок 30. НЕТ ЗАДАНИЯ", url: "https://example.com/robot8-1" },
            { id: 31, title: "Урок 31. НЕТ ЗАДАНИЯ", url: "https://example.com/robot8-1" },
            { id: 32, title: "Урок 32. НЕТ ЗАДАНИЯ", url: "https://example.com/robot8-1" },
            { id: 33, title: "Урок 33. НЕТ ЗАДАНИЯ", url: "https://example.com/robot8-1" },
            { id: 34, title: "Урок 34. НЕТ ЗАДАНИЯ", url: "https://example.com/robot8-1" },
        ]
    },
    "Робототехника": {
        "5 Класс": [
            { id: 1, title: "Урок 1. НЕТ ЗАДАНИЯ", url: "https://example.com/robot8-1" },
            { id: 2, title: "Урок 2. НЕТ ЗАДАНИЯ", url: "https://example.com/robot8-1" },
            { id: 3, title: "Урок 3. НЕТ ЗАДАНИЯ", url: "https://example.com/robot8-1" },
            { id: 4, title: "Урок 4. НЕТ ЗАДАНИЯ", url: "https://example.com/robot8-1" },
            { id: 5, title: "Урок 5. НЕТ ЗАДАНИЯ", url: "https://example.com/robot8-1" },
            { id: 6, title: "Урок 6. НЕТ ЗАДАНИЯ", url: "https://example.com/robot8-1" },
            { id: 7, title: "Урок 7. НЕТ ЗАДАНИЯ", url: "https://example.com/robot8-1" },
            { id: 8, title: "Урок 8. НЕТ ЗАДАНИЯ", url: "https://example.com/robot8-1" },
            { id: 9, title: "Урок 9. НЕТ ЗАДАНИЯ", url: "https://example.com/robot8-1" },
            { id: 10, title: "Урок 10. НЕТ ЗАДАНИЯ", url: "https://example.com/robot8-1" },
            { id: 11, title: "Урок 11. НЕТ ЗАДАНИЯ", url: "https://example.com/robot8-1" },
            { id: 12, title: "Урок 12. НЕТ ЗАДАНИЯ", url: "https://example.com/robot8-1" },
            { id: 13, title: "Урок 13. НЕТ ЗАДАНИЯ", url: "https://example.com/robot8-1" },
            { id: 14, title: "Урок 14. НЕТ ЗАДАНИЯ", url: "https://example.com/robot8-1" },
            { id: 15, title: "Урок 15. НЕТ ЗАДАНИЯ", url: "https://example.com/robot8-1" },
            { id: 16, title: "Урок 16. НЕТ ЗАДАНИЯ", url: "https://example.com/robot8-1" },
            { id: 17, title: "Урок 17. НЕТ ЗАДАНИЯ", url: "https://example.com/robot8-1" },
            { id: 18, title: "Урок 18. НЕТ ЗАДАНИЯ", url: "https://example.com/robot8-1" },
            { id: 19, title: "Урок 19. НЕТ ЗАДАНИЯ", url: "https://example.com/robot8-1" },
            { id: 20, title: "Урок 20. НЕТ ЗАДАНИЯ", url: "https://example.com/robot8-1" },
            { id: 21, title: "Урок 21. НЕТ ЗАДАНИЯ", url: "https://example.com/robot8-1" },
            { id: 22, title: "Урок 22. НЕТ ЗАДАНИЯ", url: "https://example.com/robot8-1" },
            { id: 23, title: "Урок 23. НЕТ ЗАДАНИЯ", url: "https://example.com/robot8-1" },
            { id: 24, title: "Урок 24. НЕТ ЗАДАНИЯ", url: "https://example.com/robot8-1" },
            { id: 25, title: "Урок 25. НЕТ ЗАДАНИЯ", url: "https://example.com/robot8-1" },
            { id: 26, title: "Урок 26. НЕТ ЗАДАНИЯ", url: "https://example.com/robot8-1" },
            { id: 27, title: "Урок 27. НЕТ ЗАДАНИЯ", url: "https://example.com/robot8-1" },
            { id: 28, title: "Урок 28. НЕТ ЗАДАНИЯ", url: "https://example.com/robot8-1" },
            { id: 29, title: "Урок 29. НЕТ ЗАДАНИЯ", url: "https://example.com/robot8-1" },
            { id: 30, title: "Урок 30. НЕТ ЗАДАНИЯ", url: "https://example.com/robot8-1" },
            { id: 31, title: "Урок 31. НЕТ ЗАДАНИЯ", url: "https://example.com/robot8-1" },
            { id: 32, title: "Урок 32. НЕТ ЗАДАНИЯ", url: "https://example.com/robot8-1" },
            { id: 33, title: "Урок 33. НЕТ ЗАДАНИЯ", url: "https://example.com/robot8-1" },
            { id: 34, title: "Урок 34. НЕТ ЗАДАНИЯ", url: "https://example.com/robot8-1" },
        ],
        "6 Класс": [
            { id: 1, title: "Урок 1. НЕТ ЗАДАНИЯ", url: "https://example.com/robot8-1" },
            { id: 2, title: "Урок 2. НЕТ ЗАДАНИЯ", url: "https://example.com/robot8-1" },
            { id: 3, title: "Урок 3. НЕТ ЗАДАНИЯ", url: "https://example.com/robot8-1" },
            { id: 4, title: "Урок 4. НЕТ ЗАДАНИЯ", url: "https://example.com/robot8-1" },
            { id: 5, title: "Урок 5. НЕТ ЗАДАНИЯ", url: "https://example.com/robot8-1" },
            { id: 6, title: "Урок 6. НЕТ ЗАДАНИЯ", url: "https://example.com/robot8-1" },
            { id: 7, title: "Урок 7. НЕТ ЗАДАНИЯ", url: "https://example.com/robot8-1" },
            { id: 8, title: "Урок 8. НЕТ ЗАДАНИЯ", url: "https://example.com/robot8-1" },
            { id: 9, title: "Урок 9. НЕТ ЗАДАНИЯ", url: "https://example.com/robot8-1" },
            { id: 10, title: "Урок 10. НЕТ ЗАДАНИЯ", url: "https://example.com/robot8-1" },
            { id: 11, title: "Урок 11. НЕТ ЗАДАНИЯ", url: "https://example.com/robot8-1" },
            { id: 12, title: "Урок 12. НЕТ ЗАДАНИЯ", url: "https://example.com/robot8-1" },
            { id: 13, title: "Урок 13. НЕТ ЗАДАНИЯ", url: "https://example.com/robot8-1" },
            { id: 14, title: "Урок 14. НЕТ ЗАДАНИЯ", url: "https://example.com/robot8-1" },
            { id: 15, title: "Урок 15. НЕТ ЗАДАНИЯ", url: "https://example.com/robot8-1" },
            { id: 16, title: "Урок 16. НЕТ ЗАДАНИЯ", url: "https://example.com/robot8-1" },
            { id: 17, title: "Урок 17. НЕТ ЗАДАНИЯ", url: "https://example.com/robot8-1" },
            { id: 18, title: "Урок 18. НЕТ ЗАДАНИЯ", url: "https://example.com/robot8-1" },
            { id: 19, title: "Урок 19. НЕТ ЗАДАНИЯ", url: "https://example.com/robot8-1" },
            { id: 20, title: "Урок 20. НЕТ ЗАДАНИЯ", url: "https://example.com/robot8-1" },
            { id: 21, title: "Урок 21. НЕТ ЗАДАНИЯ", url: "https://example.com/robot8-1" },
            { id: 22, title: "Урок 22. НЕТ ЗАДАНИЯ", url: "https://example.com/robot8-1" },
            { id: 23, title: "Урок 23. НЕТ ЗАДАНИЯ", url: "https://example.com/robot8-1" },
            { id: 24, title: "Урок 24. НЕТ ЗАДАНИЯ", url: "https://example.com/robot8-1" },
            { id: 25, title: "Урок 25. НЕТ ЗАДАНИЯ", url: "https://example.com/robot8-1" },
            { id: 26, title: "Урок 26. НЕТ ЗАДАНИЯ", url: "https://example.com/robot8-1" },
            { id: 27, title: "Урок 27. НЕТ ЗАДАНИЯ", url: "https://example.com/robot8-1" },
            { id: 28, title: "Урок 28. НЕТ ЗАДАНИЯ", url: "https://example.com/robot8-1" },
            { id: 29, title: "Урок 29. НЕТ ЗАДАНИЯ", url: "https://example.com/robot8-1" },
            { id: 30, title: "Урок 30. НЕТ ЗАДАНИЯ", url: "https://example.com/robot8-1" },
            { id: 31, title: "Урок 31. НЕТ ЗАДАНИЯ", url: "https://example.com/robot8-1" },
            { id: 32, title: "Урок 32. НЕТ ЗАДАНИЯ", url: "https://example.com/robot8-1" },
            { id: 33, title: "Урок 33. НЕТ ЗАДАНИЯ", url: "https://example.com/robot8-1" },
            { id: 34, title: "Урок 34. НЕТ ЗАДАНИЯ", url: "https://example.com/robot8-1" },
        ],
        "7 Класс": [
            { id: 1, title: "Урок 1. НЕТ ЗАДАНИЯ", url: "https://example.com/robot7-1" },
            { id: 2, title: "Урок 2. НЕТ ЗАДАНИЯ", url: "https://example.com/robot7-1" },
            { id: 3, title: "Урок 3. Собери робота (образец)", url: "https://drive.google.com/file/d/1yRqFD2dJa5uBIOIiQfZAeJEfzYxHAjcU/view?usp=drive_link" },
            { id: 4, title: "Урок 4. НЕТ ЗАДАНИЯ", url: "https://example.com/robot8-1" },
            { id: 5, title: "Урок 5. НЕТ ЗАДАНИЯ", url: "https://example.com/robot8-1" },
            { id: 6, title: "Урок 6. НЕТ ЗАДАНИЯ", url: "https://example.com/robot8-1" },
            { id: 7, title: "Урок 7. НЕТ ЗАДАНИЯ", url: "https://example.com/robot8-1" },
            { id: 8, title: "Урок 8. НЕТ ЗАДАНИЯ", url: "https://example.com/robot8-1" },
            { id: 9, title: "Урок 9. НЕТ ЗАДАНИЯ", url: "https://example.com/robot8-1" },
            { id: 10, title: "Урок 10. НЕТ ЗАДАНИЯ", url: "https://example.com/robot8-1" },
            { id: 11, title: "Урок 11. НЕТ ЗАДАНИЯ", url: "https://example.com/robot8-1" },
            { id: 12, title: "Урок 12. НЕТ ЗАДАНИЯ", url: "https://example.com/robot8-1" },
            { id: 13, title: "Урок 13. НЕТ ЗАДАНИЯ", url: "https://example.com/robot8-1" },
            { id: 14, title: "Урок 14. НЕТ ЗАДАНИЯ", url: "https://example.com/robot8-1" },
            { id: 15, title: "Урок 15. НЕТ ЗАДАНИЯ", url: "https://example.com/robot8-1" },
            { id: 16, title: "Урок 16. НЕТ ЗАДАНИЯ", url: "https://example.com/robot8-1" },
            { id: 17, title: "Урок 17. НЕТ ЗАДАНИЯ", url: "https://example.com/robot8-1" },
            { id: 18, title: "Урок 18. НЕТ ЗАДАНИЯ", url: "https://example.com/robot8-1" },
            { id: 19, title: "Урок 19. НЕТ ЗАДАНИЯ", url: "https://example.com/robot8-1" },
            { id: 20, title: "Урок 20. НЕТ ЗАДАНИЯ", url: "https://example.com/robot8-1" },
            { id: 21, title: "Урок 21. НЕТ ЗАДАНИЯ", url: "https://example.com/robot8-1" },
            { id: 22, title: "Урок 22. НЕТ ЗАДАНИЯ", url: "https://example.com/robot8-1" },
            { id: 23, title: "Урок 23. НЕТ ЗАДАНИЯ", url: "https://example.com/robot8-1" },
            { id: 24, title: "Урок 24. НЕТ ЗАДАНИЯ", url: "https://example.com/robot8-1" },
            { id: 25, title: "Урок 25. НЕТ ЗАДАНИЯ", url: "https://example.com/robot8-1" },
            { id: 26, title: "Урок 26. НЕТ ЗАДАНИЯ", url: "https://example.com/robot8-1" },
            { id: 27, title: "Урок 27. НЕТ ЗАДАНИЯ", url: "https://example.com/robot8-1" },
            { id: 28, title: "Урок 28. НЕТ ЗАДАНИЯ", url: "https://example.com/robot8-1" },
            { id: 29, title: "Урок 29. НЕТ ЗАДАНИЯ", url: "https://example.com/robot8-1" },
            { id: 30, title: "Урок 30. НЕТ ЗАДАНИЯ", url: "https://example.com/robot8-1" },
            { id: 31, title: "Урок 31. НЕТ ЗАДАНИЯ", url: "https://example.com/robot8-1" },
            { id: 32, title: "Урок 32. НЕТ ЗАДАНИЯ", url: "https://example.com/robot8-1" },
            { id: 33, title: "Урок 33. НЕТ ЗАДАНИЯ", url: "https://example.com/robot8-1" },
            { id: 34, title: "Урок 34. НЕТ ЗАДАНИЯ", url: "https://example.com/robot8-1" },
        ],
        "8 Класс": [
            { id: 1, title: "Урок 1. НЕТ ЗАДАНИЯ", url: "https://example.com/robot8-1" },
            { id: 2, title: "Урок 2. НЕТ ЗАДАНИЯ", url: "https://example.com/robot8-1" },
            { id: 3, title: "Урок 3. НЕТ ЗАДАНИЯ", url: "https://example.com/robot8-1" },
            { id: 4, title: "Урок 4. НЕТ ЗАДАНИЯ", url: "https://example.com/robot8-1" },
            { id: 5, title: "Урок 5. Бегущие огни", url: "https://drive.google.com/file/d/1hcVG_FeCYtH05cH4tf9q00wGG8_JpAK0/view?usp=drive_link" },
            { id: 6, title: "Урок 6. Кнопка", url: "https://drive.google.com/file/d/1PYynVxr-is6FipuJjbwveGxQCTxSsHk8/view?usp=sharing" },
            { id: 7, title: "Урок 7. НЕТ ЗАДАНИЯ", url: "https://example.com/robot8-1" },
            { id: 8, title: "Урок 8. НЕТ ЗАДАНИЯ", url: "https://example.com/robot8-1" },
            { id: 9, title: "Урок 9. НЕТ ЗАДАНИЯ", url: "https://example.com/robot8-1" },
            { id: 10, title: "Урок 10. НЕТ ЗАДАНИЯ", url: "https://example.com/robot8-1" },
            { id: 11, title: "Урок 11. НЕТ ЗАДАНИЯ", url: "https://example.com/robot8-1" },
            { id: 12, title: "Урок 12. НЕТ ЗАДАНИЯ", url: "https://example.com/robot8-1" },
            { id: 13, title: "Урок 13. НЕТ ЗАДАНИЯ", url: "https://example.com/robot8-1" },
            { id: 14, title: "Урок 14. НЕТ ЗАДАНИЯ", url: "https://example.com/robot8-1" },
            { id: 15, title: "Урок 15. НЕТ ЗАДАНИЯ", url: "https://example.com/robot8-1" },
            { id: 16, title: "Урок 16. НЕТ ЗАДАНИЯ", url: "https://example.com/robot8-1" },
            { id: 17, title: "Урок 17. НЕТ ЗАДАНИЯ", url: "https://example.com/robot8-1" },
            { id: 18, title: "Урок 18. НЕТ ЗАДАНИЯ", url: "https://example.com/robot8-1" },
            { id: 19, title: "Урок 19. НЕТ ЗАДАНИЯ", url: "https://example.com/robot8-1" },
            { id: 20, title: "Урок 20. НЕТ ЗАДАНИЯ", url: "https://example.com/robot8-1" },
            { id: 21, title: "Урок 21. НЕТ ЗАДАНИЯ", url: "https://example.com/robot8-1" },
            { id: 22, title: "Урок 22. НЕТ ЗАДАНИЯ", url: "https://example.com/robot8-1" },
            { id: 23, title: "Урок 23. НЕТ ЗАДАНИЯ", url: "https://example.com/robot8-1" },
            { id: 24, title: "Урок 24. НЕТ ЗАДАНИЯ", url: "https://example.com/robot8-1" },
            { id: 25, title: "Урок 25. НЕТ ЗАДАНИЯ", url: "https://example.com/robot8-1" },
            { id: 26, title: "Урок 26. НЕТ ЗАДАНИЯ", url: "https://example.com/robot8-1" },
            { id: 27, title: "Урок 27. НЕТ ЗАДАНИЯ", url: "https://example.com/robot8-1" },
            { id: 28, title: "Урок 28. НЕТ ЗАДАНИЯ", url: "https://example.com/robot8-1" },
            { id: 29, title: "Урок 29. НЕТ ЗАДАНИЯ", url: "https://example.com/robot8-1" },
            { id: 30, title: "Урок 30. НЕТ ЗАДАНИЯ", url: "https://example.com/robot8-1" },
            { id: 31, title: "Урок 31. НЕТ ЗАДАНИЯ", url: "https://example.com/robot8-1" },
            { id: 32, title: "Урок 32. НЕТ ЗАДАНИЯ", url: "https://example.com/robot8-1" },
            { id: 33, title: "Урок 33. НЕТ ЗАДАНИЯ", url: "https://example.com/robot8-1" },
            { id: 34, title: "Урок 34. НЕТ ЗАДАНИЯ", url: "https://example.com/robot8-1" },
            // ...
        ]
    }
};

// Функция-помощник для генерации шаблона из 34 уроков, если ссылки ещё не запущены
function getLessonsFor(subject, className) {
    if (lessonsData[subject] && lessonsData[subject][className]) {
        return lessonsData[subject][className];
    }
    
    // Если для класса пока нет индивидуального списка, генерируются 34 базовых урока
    return Array.from({ length: 34 }, (_, i) => ({
        id: i + 1,
        title: `Урок ${i + 1}. Тема занятия`,
        url: "#"
    }));
}